//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNCHITIET
    {
        public string IdCN { get; set; }
        public string IdNCU { get; set; }
        public string TenNCU { get; set; }
        public string SĐT { get; set; }
        public string DiaChi { get; set; }
        public double Conno { get; set; }
    
        public virtual CONGNO CONGNO { get; set; }
        public virtual NHACUNGUNG NHACUNGUNG { get; set; }
    }
}
