//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU
    {
        public string IdDT { get; set; }
        public string IdNV { get; set; }
        public double Doanhsoban { get; set; }
        public double Doanhthubh { get; set; }
        public double Loinhuan { get; set; }
        public System.DateTime NgayTK { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
