//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDBANCHITIET
    {
        public string IdHDB { get; set; }
        public string IdSP { get; set; }
        public double SL { get; set; }
        public double Dongiaban { get; set; }
        public double Giamgia { get; set; }
        public double Thanhtien { get; set; }
    
        public virtual HOADONBAN HOADONBAN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
