//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONNHAP()
        {
            this.HDNHAPCHITIETs = new HashSet<HDNHAPCHITIET>();
        }
    
        public string IdHDN { get; set; }
        public string IdNV { get; set; }
        public string IdNCU { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public Nullable<double> SL { get; set; }
        public Nullable<double> Tongtien { get; set; }
        public Nullable<double> Dathanhtoan { get; set; }
        public Nullable<double> Conno { get; set; }
        public string NgayHHTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDNHAPCHITIET> HDNHAPCHITIETs { get; set; }
        public virtual NHACUNGUNG NHACUNGUNG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
