//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONBAN()
        {
            this.HDBANCHITIETs = new HashSet<HDBANCHITIET>();
        }
    
        public string IdHDB { get; set; }
        public string IdNV { get; set; }
        public string IdKH { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public Nullable<double> SL { get; set; }
        public Nullable<double> Tongtien { get; set; }
        public string HinhThucTT { get; set; }
        public Nullable<double> Dathanhtoan { get; set; }
        public Nullable<double> Conno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDBANCHITIET> HDBANCHITIETs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
