//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADONBANs = new HashSet<HOADONBAN>();
        }
    
        public string IdKH { get; set; }
        public string TenKH { get; set; }
        public string NgaySinh { get; set; }
        public string Gioitinh { get; set; }
        public string SoCMND { get; set; }
        public string DiaChi { get; set; }
        public string SĐT { get; set; }
        public string LoaiKH { get; set; }
        public Nullable<double> Conno { get; set; }
        public string Danhgia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBAN> HOADONBANs { get; set; }
    }
}
