//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_DUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOI_DUNG()
        {
            this.TRUY_CAP = new HashSet<TRUY_CAP>();
        }
    
        public string IdND { get; set; }
        public string IdNND { get; set; }
        public string IdNV { get; set; }
        public string TenND { get; set; }
        public string TenTK { get; set; }
        public string PassWord { get; set; }
        public string NgayTaoTK { get; set; }
        public string DanhmucTC { get; set; }
        public string QuyenDM { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHOM_NGUOI_DUNG NHOM_NGUOI_DUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRUY_CAP> TRUY_CAP { get; set; }
    }
}
