//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_NGUOI_DUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOM_NGUOI_DUNG()
        {
            this.NGUOI_DUNG = new HashSet<NGUOI_DUNG>();
        }
    
        public string IdNND { get; set; }
        public string IdNhomQH { get; set; }
        public string TenNND { get; set; }
        public string MoTaNND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual NHOM_QUYEN_HAN NHOM_QUYEN_HAN { get; set; }
    }
}
