//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.HDBANCHITIETs = new HashSet<HDBANCHITIET>();
            this.HDNHAPCHITIETs = new HashSet<HDNHAPCHITIET>();
            this.HTCHITIETs = new HashSet<HTCHITIET>();
        }
    
        public string IdSP { get; set; }
        public string IdNCU { get; set; }
        public string TenSP { get; set; }
        public string NgaySX { get; set; }
        public string NgayHH { get; set; }
        public string NgayNhap { get; set; }
        public string NhaSX { get; set; }
        public double SLNhap { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> DonGiaBanLe { get; set; }
        public Nullable<double> DonGiaBanSi { get; set; }
        public string Donvi { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public string AnhSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDBANCHITIET> HDBANCHITIETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDNHAPCHITIET> HDNHAPCHITIETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTCHITIET> HTCHITIETs { get; set; }
        public virtual NHACUNGUNG NHACUNGUNG { get; set; }
    }
}
