//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Entities_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUY_CAP
    {
        public string IdTC { get; set; }
        public string IdND { get; set; }
        public string TenTK { get; set; }
        public string LanDMKCuoi { get; set; }
        public string LanDNCuoi { get; set; }
        public string DanhmucTC { get; set; }
        public string Thaotac { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
    }
}
